version: "2"
linters:
  enable:
    - gosec
    - gocritic
    - ineffassign
    - unconvert
    - gocyclo
    - misspell
    - unused
    - prealloc
    - bodyclose
    - errcheck
    - goconst
    - whitespace
    - lll
  settings:
    lll:
      line-length: 100
    gocyclo:
      min-complexity: 10
run:
  timeout: 3m
  tests: true