services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network