services:
  subscription-service:
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile
      target: final
    ports:
      - "8001:8000"
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      weather-service:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/metrics" ]
      interval: 5s
      timeout: 10s
      retries: 5
  weather-service:
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
      target: final
    ports:
      - "8000:8000"
      - "50051:50051"
    volumes:
      - ./logs:/logs
    depends_on:
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/metrics"]
      interval: 5s
      timeout: 10s
      retries: 5
  gateway-service:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
      target: final
    ports:
      - "8080:8080"
    depends_on:
      weather-service:
        condition: service_healthy
    networks:
      - app-network
  notification-service:
    build:
      context: .
      dockerfile: apps/notification/Dockerfile
      target: final
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - app-network
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - app-network
    healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 5
  loki:
    image: grafana/loki:latest
    user: "0"
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./monitoring/loki/loki-data:/loki
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-S", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/config:/etc/prometheus
      - ./monitoring/prometheus/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./monitoring/grafana/grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypass
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5