global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'weather-api-monitoring'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/metrics'
