services:
  smtp-server:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: weather-api-mock
    ports:
      - "8081:8080"
    volumes:
      - ./weather-api-mock/files:/home/wiremock/__files
      - ./weather-api-mock/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true