apiVersion: 1

datasources:
  - name: Weather-Api Metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki Logs
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false