name: architecture-tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-architecture-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Install protoc and plugins
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Generate gRPC and Protobuf files
        run: make proto-gen-all

      - name: Run tests
        run: make architecture
