name: e2e-tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare logs directory with correct permissions
        run: |
            mkdir -p ./logs
            chmod 777 ./logs

      - name: Set up Docker Buildx
        run: make install-playwright

      - name: Run tests
        run: make e2e