name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - apps/subscription
          - apps/weather
          - apps/notification
          - apps/gateway
          - apps/email
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ${{ matrix.module }}
          args: --config=../../.golangci.yml
