name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Install protoc and plugins
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Generate gRPC and Protobuf files
        run: make proto-gen-all

      - name: Run tests
        run: make unit